allowBuilds:
  core-js: set this to true or false
  esbuild: set this to true or false
minimumReleaseAgeExclude:
  - '@next/env@16.3.0'
  - '@next/swc-darwin-arm64@16.3.0'
  - '@next/swc-darwin-x64@16.3.0'
  - '@next/swc-linux-arm64-gnu@16.3.0'
  - '@next/swc-linux-arm64-musl@16.3.0'
  - '@next/swc-linux-x64-gnu@16.3.0'
  - '@next/swc-linux-x64-musl@16.3.0'
  - '@next/swc-win32-arm64-msvc@16.3.0'
  - '@next/swc-win32-x64-msvc@16.3.0'
  - next@16.3.0
